
<a class="twitter-timeline" data-dnt="true" width="300" height="300"  href="https://twitter.com/Dasygenis"  data-widget-id="327111652677910528">Tweets σχετικά με @Dasygenis</a>
<script type="text/javascript">!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>



